name: Test suite

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.38'
          - '5.36'
          - '5.34'
          - '5.32'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: perl -V
      - run: cpanm --notest --installdeps --verbose .
      - run: perl -c -Ilib bin/check_raid.pl
      - run: make test
      - run: make pack
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: perl-file-${{ matrix.perl-version }}
          path: bin/check_raid.pl
